/**
 * TypeScript definitions for Electron desktopAPI
 * This API is exposed via contextBridge in electron/preload.js
 */
export interface DesktopAPI {
  // Database operations
  getNotes: () => Promise<any[]>;
  getNote: (id: string) => Promise<any | undefined>;
  createNote: (data: {
    id: string;
    title: string;
    content: string;
    tags: string; // JSON string
    createdAt: number;
    updatedAt: number;
    embedding: string | null; // JSON string or null
    screenshot?: string | null;
    coverImagePath?: string | null;
    iconPath?: string | null;
    iconEmoji?: string | null;
    autoGeneratedTitle?: number; // 0 or 1
    autoGeneratedTags?: number; // 0 or 1
  }) => Promise<void>;
  updateNote: (id: string, updates: {
    title?: string;
    content?: string;
    tags?: string;
    updatedAt?: number;
    embedding?: string | null;
    screenshot?: string | null;
    screenshotPath?: string | null;
    coverImagePath?: string | null;
    iconPath?: string | null;
    iconEmoji?: string | null;
    autoGeneratedTitle?: number; // 0 or 1
    autoGeneratedTags?: number; // 0 or 1
  }) => Promise<void>;
  deleteNote: (id: string) => Promise<void>;
  getNotesByTag: (tag: string) => Promise<any[]>;
  searchNotesByText: (query: string) => Promise<any[]>;
  getAllTags: () => Promise<string[]>;
  // Embedding operations
  generateEmbedding: (text: string) => Promise<number[]>;
  semanticSearch: (queryEmbedding: number[]) => Promise<any[]>;
  // AI operations
  generateNoteTitle: (content: string) => Promise<string>;
  generateNoteTags: (content: string) => Promise<string[]>;
  // Screenshot operations
  captureScreenshot: (noteId: string) => Promise<string | null>;
  // Quick Capture operations
  updateQuickNote: (content: string) => Promise<{ success: boolean; id: string }>;
  closeQuickCapture: () => Promise<void>;
  // Cover Image operations
  selectCoverImage: () => Promise<string | null>;
  saveCoverImage: (sourcePath: string, noteId: string) => Promise<string | null>;
  deleteCoverImage: (imagePath: string) => Promise<boolean>;
  // App Logo operations
  uploadAppLogo: () => Promise<string | null>;
  getAppLogo: () => Promise<string | null>;
  // Note Icon operations
  saveNoteIcon: (sourcePath: string, noteId: string) => Promise<string | null>;
  // General Image operations
  saveImage: (arrayBuffer: ArrayBuffer, filename: string) => Promise<string | null>;
}

declare global {
  interface Window {
    desktopAPI?: DesktopAPI;
  }
}

