export interface Note {
  id: string;
  title: string;
  content: string;
  tags: string[];
  createdAt: number;
  updatedAt: number;
  embedding: number[] | null; // Vector embedding for semantic search
  screenshot?: string; // Optional field for future use
  screenshotPath?: string; // Path to screenshot file
  coverImagePath?: string; // Path to cover image file
  autoGeneratedTitle?: boolean; // Whether title was AI-generated
  autoGeneratedTags?: boolean; // Whether tags were AI-generated
}

export interface Tag {
  id: string;
  name: string;
  color?: string;
  count: number;
}

export interface Relationship {
  id: string;
  sourceNoteId: string;
  targetNoteId: string;
  type: 'related' | 'references' | 'similar';
  strength: number; // 0-1, based on similarity or explicit link
  createdAt: number;
}

export interface NoteSearchResult {
  note: Note;
  score: number; // Relevance score for search
}

