export interface Note {
  id: string;
  title: string;
  content: string;
  parentId?: string | null; // Parent note ID for nested pages (null for root-level notes)
  tags: string[];
  createdAt: number;
  updatedAt: number;
  embedding: number[] | null; // Vector embedding for semantic search
  screenshot?: string; // Optional field for future use
  screenshotPath?: string; // Path to screenshot file
  coverImagePath?: string; // Path to cover image file
  iconPath?: string; // Path to custom note icon file
  iconEmoji?: string; // Custom emoji for note icon
  autoGeneratedTitle?: boolean; // Whether title was AI-generated
  autoGeneratedTags?: boolean; // Whether tags were AI-generated
  isFavorite?: boolean; // Whether note is favorited
  status?: 'todo' | 'in-progress' | 'done'; // Kanban status
  priority?: 'low' | 'medium' | 'high'; // Priority level
}

export interface Tag {
  id: string;
  name: string;
  color?: string;
  count: number;
}

export interface Relationship {
  id: string;
  sourceNoteId: string;
  targetNoteId: string;
  type: 'related' | 'references' | 'similar';
  strength: number; // 0-1, based on similarity or explicit link
  createdAt: number;
}

export interface NoteSearchResult {
  note: Note;
  score: number; // Relevance score for search
}

