import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";

export const notes = sqliteTable("notes", {
  id: text("id").primaryKey(),
  title: text("title"),
  content: text("content"),
  tags: text("tags"), // store JSON string: ["tag1","tag2"]
  createdAt: integer("created_at"),
  updatedAt: integer("updated_at"),
  embedding: text("embedding"), // store as JSON for now
  screenshot: text("screenshot"), // optional field for future use
  screenshotPath: text("screenshot_path"), // path to screenshot file
  coverImagePath: text("cover_image_path"), // path to cover image file
  autoGeneratedTitle: integer("auto_generated_title"), // 0 or 1
  autoGeneratedTags: integer("auto_generated_tags"), // 0 or 1
});

