const { sqliteTable, text, integer } = require("drizzle-orm/sqlite-core");

const notes = sqliteTable("notes", {
  id: text("id").primaryKey(),
  title: text("title"),
  content: text("content"),
  tags: text("tags"), // store JSON string: ["tag1","tag2"]
  createdAt: integer("created_at"),
  updatedAt: integer("updated_at"),
  embedding: text("embedding"), // store as JSON for now
  screenshot: text("screenshot"),
  screenshotPath: text("screenshot_path"),
  coverImagePath: text("cover_image_path"),
  iconPath: text("icon_path"),
  iconEmoji: text("icon_emoji"),
  autoGeneratedTitle: integer("auto_generated_title"),
  autoGeneratedTags: integer("auto_generated_tags"),
});

module.exports = { notes };

